### ISSUE TITLE
Make App responsive for more different types of screen sizes

### ISSUE THREAD

**Issue by abhinav2712** [abhinav2712/Planets.io#6]
Try to make the app responsive for every screen size possible (large, medium and small)
Look out for the dimensions from net

**Comment by Rishav1707** [comment]
Shall I work on this?? @abhinav2712

**Comment by abhinav2712** [comment]
> Shall I work on this?? @abhinav2712 

Yes, make the hamburger option work as well if possible

**Comment by Rishav1707** [comment]
OK @abhinav2712 I will try
